--Tasks 3: Aggregate functions, Having, Order By, GroupBy and Joins

--1. Write a SQL query to List Events and Their Average Ticket Prices. 
select event_name, avg(ticket_price) as avg_ticket_price from event group by event_name;

--2. Write a SQL query to Calculate the Total Revenue Generated by Events. 
select e.event_name, sum(b.total_cost) as total_revenue from booking b join event e on b.event_id = e.event_id group by e.event_name;

--3. Write a SQL query to find the event with the highest ticket sales. 
select top 1 e.event_name, sum(b.num_tickets) as total_tickets_sold from booking b join event e on b.event_id = e.event_id 
group by e.event_name  order by total_tickets_sold desc;

--4. Write a SQL query to Calculate the Total Number of Tickets Sold for Each Event.  
select e.event_name, sum(b.num_tickets) as total_tickets_sold from booking b join event e on b.event_id = e.event_id group by e.event_name;  

--5. Write a SQL query to Find Events with No Ticket Sales.  
select e.event_name from event e left join booking b on e.event_id = b.event_id where b.event_id is null;  

--6. Write a SQL query to Find the User Who Has Booked the Most Tickets.  
select top 1 c.customer_name, sum(b.num_tickets) as total_tickets from booking b join customer c on b.customer_id = c.customer_id  
group by c.customer_name order by total_tickets desc;  

--7. Write a SQL query to List Events and the total number of tickets sold for each month.  
select month(e.event_date) as event_month, year(e.event_date) as event_year, e.event_name, sum(b.num_tickets) as total_tickets  
from booking b join event e on b.event_id = e.event_id  
group by month(e.event_date), year(e.event_date), e.event_name  
order by event_year, event_month;  

--8. Write a SQL query to calculate the average Ticket Price for Events in Each Venue.  
select v.venue_name, avg(e.ticket_price) as avg_ticket_price from event e join venue v on e.venue_id = v.venue_id group by v.venue_name;  

--9. Write a SQL query to calculate the total Number of Tickets Sold for Each Event Type.  
select e.event_type, sum(b.num_tickets) as total_tickets_sold from booking b join event e on b.event_id = e.event_id group by e.event_type;  

--10. Write a SQL query to calculate the total Revenue Generated by Events in Each Year.  
select year(e.event_date) as event_year, sum(b.total_cost) as total_revenue from booking b join event e on b.event_id = e.event_id  
group by year(e.event_date) order by event_year;  

--11. Write a SQL query to list users who have booked tickets for multiple events.  
select c.customer_name, count(distinct b.event_id) as total_events_booked from booking b join customer c on b.customer_id = c.customer_id  
group by c.customer_name having count(distinct b.event_id) > 1;  

--12. Write a SQL query to calculate the Total Revenue Generated by Events for Each User.  
select c.customer_name, sum(b.total_cost) as total_revenue from booking b join customer c on b.customer_id = c.customer_id  
group by c.customer_name order by total_revenue desc;  

--13. Write a SQL query to calculate the Average Ticket Price for Events in Each Category and Venue.  
select e.event_type, v.venue_name, avg(e.ticket_price) as avg_ticket_price  
from event e join venue v on e.venue_id = v.venue_id  
group by e.event_type, v.venue_name;  

--1. Calculate the Average Ticket Price for Events in Each Venue Using a Subquery.  
select venue_name, (select avg(ticket_price) from event e where e.venue_id = v.venue_id) as avg_ticket_price  
from venue v;  

--2. Find Events with More Than 50% of Tickets Sold using subquery.  
select event_name from event  
where (total_seats - available_seats) > (total_seats * 0.5);  

--3. Calculate the Total Number of Tickets Sold for Each Event.  
select event_name, (select sum(num_tickets) from booking b where b.event_id = e.event_id) as total_tickets_sold  
from event e;  

--4. Find Users Who Have Not Booked Any Tickets Using a NOT EXISTS Subquery.  
select customer_name from customer c  
where not exists (select 1 from booking b where b.customer_id = c.customer_id);  

--5. List Events with No Ticket Sales Using a NOT IN Subquery.  
select event_name from event  
where event_id not in (select distinct event_id from booking);  

--6. Calculate the Total Number of Tickets Sold for Each Event Type Using a Subquery in the FROM Clause.  
select e.event_type, total_tickets_sold  
from (select event_type, sum(num_tickets) as total_tickets_sold  
      from booking b join event e on b.event_id = e.event_id  
      group by e.event_type) as subquery;  

--7. Find Events with Ticket Prices Higher Than the Average Ticket Price Using a Subquery in the WHERE Clause.  
select event_name, ticket_price from event  
where ticket_price > (select avg(ticket_price) from event);  

--8. Calculate the Total Revenue Generated by Events for Each User Using a Correlated Subquery.  
select c.customer_name,  
       (select sum(b.total_cost) from booking b where b.customer_id = c.customer_id) as total_revenue  
from customer c;  

--9. List Users Who Have Booked Tickets for Events in a Given Venue Using a Subquery in the WHERE Clause.  
select customer_name from customer  
where customer_id in (select distinct b.customer_id from booking b  
                      join event e on b.event_id = e.event_id  
                      where e.venue_id = 1); -- Change '1' to the specific venue_id  

--10. Calculate the Total Number of Tickets Sold for Each Event Category Using a Subquery with GROUP BY.  
select event_type,  
       (select sum(num_tickets) from booking b where b.event_id = e.event_id) as total_tickets_sold  
from event e group by event_type;  

--11. Find Users Who Have Booked Tickets for Events in each Month Using a Subquery with DATE_FORMAT.  
select distinct c.customer_name  
from customer c  
where c.customer_id in (select b.customer_id from booking b  
                        where month(b.booking_date) = 4 and year(b.booking_date) = 2025);  

--12. Calculate the Average Ticket Price for Events in Each Venue Using a Subquery.  
select venue_name, (select avg(ticket_price) from event e where e.venue_id = v.venue_id) as avg_ticket_price  
from venue v;  
